from pathlib import Path
import csv, re, sys

ROOT = Path(__file__).resolve().parents[1]
summary_path = ROOT/'results'/'provenancebench_method_summary.csv'
stats_path = ROOT/'results'/'provenancebench_strict_stats.csv'
paper_path = ROOT/'paper'/'main.tex'
readme_path = ROOT/'README.md'
results_card_path = ROOT/'RESULTS_CARD.md'
ledger_path = ROOT/'docs'/'CLAIM_LEDGER.md'


def load_rows(path):
    with path.open(newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))

summary = load_rows(summary_path)
stats = load_rows(stats_path)

def row(method, split):
    for r in summary:
        if r['method']==method and r['split']==split:
            return r
    raise KeyError((method, split))

def srow(split):
    for r in stats:
        if r['split']==split:
            return r
    raise KeyError(split)

claims = [
    ('Hybrid PLP ID exact', float(row('hybrid_plp','test')['exact_license_match']), 'results/provenancebench_method_summary.csv', 'scripts/run_provenancebench_learned.py'),
    ('Hybrid PLP domain-OOD exact', float(row('hybrid_plp','ood_test')['exact_license_match']), 'results/provenancebench_method_summary.csv', 'scripts/run_provenancebench_learned.py'),
    ('Hybrid PLP compositional exact', float(row('hybrid_plp','compositional_test')['exact_license_match']), 'results/provenancebench_method_summary.csv', 'scripts/run_provenancebench_learned.py'),
    ('Hybrid PLP provenance-intervention exact', float(row('hybrid_plp','provenance_intervention')['exact_license_match']), 'results/provenancebench_method_summary.csv', 'scripts/run_provenancebench_learned.py'),
    ('Learned PLP domain-OOD exact', float(row('learned_plp','ood_test')['exact_license_match']), 'results/provenancebench_method_summary.csv', 'scripts/run_provenancebench_learned.py'),
    ('Learned PLP compositional exact', float(row('learned_plp','compositional_test')['exact_license_match']), 'results/provenancebench_method_summary.csv', 'scripts/run_provenancebench_learned.py'),
    ('No-provenance intervention exact', float(row('learned_no_provenance','provenance_intervention')['exact_license_match']), 'results/provenancebench_method_summary.csv', 'scripts/run_provenancebench_learned.py'),
    ('Hybrid PLP domain-OOD leakage', float(row('hybrid_plp','ood_test')['unsupported_leakage']), 'results/provenancebench_method_summary.csv', 'scripts/run_provenancebench_learned.py'),
    ('Hybrid PLP domain-OOD CI low', float(srow('ood_test')['hybrid_ci_low']), 'results/provenancebench_strict_stats.csv', 'scripts/provenancebench_stats_strict.py'),
    ('Hybrid PLP domain-OOD CI high', float(srow('ood_test')['hybrid_ci_high']), 'results/provenancebench_strict_stats.csv', 'scripts/provenancebench_stats_strict.py'),
    ('Hybrid PLP compositional CI low', float(srow('compositional_test')['hybrid_ci_low']), 'results/provenancebench_strict_stats.csv', 'scripts/provenancebench_stats_strict.py'),
    ('Hybrid PLP compositional CI high', float(srow('compositional_test')['hybrid_ci_high']), 'results/provenancebench_strict_stats.csv', 'scripts/provenancebench_stats_strict.py'),
]

# Exact benchmark cardinalities from current frozen dataset.
bench = ROOT/'datasets'/'provenance'/'provenancebench.csv'
with bench.open(newline='', encoding='utf-8') as f:
    n_bench = sum(1 for _ in f) - 1
claims.append(('ProvenanceBench examples', float(n_bench), 'datasets/provenance/provenancebench.csv', 'scripts/run_provenancebench_learned.py'))
paired = ROOT/'datasets'/'provenance'/'provenance_intervention_test.csv'
with paired.open(newline='', encoding='utf-8') as f:
    n_pair_rows = sum(1 for _ in f) - 1
claims.append(('Paired intervention examples', float(n_pair_rows), 'datasets/provenance/provenance_intervention_test.csv', 'scripts/build_provenance_intervention.py'))

# Write a human-readable ledger.
lines = [
    '# Claim Ledger',
    '',
    'Every headline quantitative claim in the paper and public-facing summaries should trace to a frozen result artifact and an executable producer. This file is generated by `scripts/claim_audit.py`.',
    '',
    '| Claim | Value | Source artifact | Producer |',
    '|---|---:|---|---|',
]
for name, value, source, producer in claims:
    if value.is_integer(): val = str(int(value))
    else: val = f'{value:.6f}'.rstrip('0').rstrip('.')
    lines.append(f'| {name} | {val} | `{source}` | `{producer}` |')
lines += [
    '',
    '## Claim boundary',
    '',
    '- These values characterize the controlled licensing benchmark and router, not end-to-end frontier-model generation.',
    '- Human-validation results are not claimed until completed annotations are supplied to the aggregation script.',
    '- Generation-compliance results are not claimed until a real model adapter is executed.',
]
ledger_path.write_text('\n'.join(lines)+'\n', encoding='utf-8')

# Fail on known stale headline numbers in paper/public summaries.
texts = {p: p.read_text(encoding='utf-8') for p in [paper_path, readme_path, results_card_path]}
# Paper must contain current central values in human-rounded form.
required_paper = ['.947', '.800', '.750', '4,800', '800 examples']
missing = [x for x in required_paper if x not in texts[paper_path]]
if missing:
    print('FAIL claim audit: paper missing current claims:', ', '.join(missing))
    sys.exit(1)
# Guard against the older overly-clean OOD/compositional headline pair.
for p, txt in texts.items():
    if re.search(r'Domain[- ]OOD[^\n]{0,80}1\.000', txt, flags=re.I):
        print(f'FAIL claim audit: stale perfect Domain-OOD claim in {p}')
        sys.exit(1)

print(f'claim audit PASS: {len(claims)} traceable claims; ledger updated')
