from pathlib import Path
import pandas as pd
root=Path(__file__).resolve().parents[1]
df=pd.read_csv(root/'results/benchmark_results.csv')
# surface worst rows per policy by overall, then by sycophancy
parts=['# Automatically Mined Failure Atlas','', 'This report surfaces low-scoring or high-sycophancy proxy outputs for manual inspection. Scores are generated by the local auditable rubric.','']
for p,g in df.groupby('policy'):
    parts += [f'## {p}','']
    worst=g.sort_values(['overall','sycophancy'],ascending=[True,False]).head(12)
    for _,r in worst.iterrows():
        parts += [f"### {r.scenario_id} — {r.category} / {r.profile} / {r.language}",
                  f"- Overall: **{r.overall:.3f}**; truthfulness: {r.truthfulness:.3f}; sycophancy: {r.sycophancy:.3f}; personalization: {r.personalization:.3f}",
                  f"- Response: {r.response}",'']
(root/'reports/FAILURE_ATLAS.md').write_text('\n'.join(parts))
print('wrote failure atlas')
