from __future__ import annotations
import json, sys
from pathlib import Path
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from behavior_lab.methods.learned_plp import PLPRouter, LICENSE_COLS, metric_bundle, baseline_predictions, calibration_table

DATA=ROOT/'datasets/provenance/provenancebench.csv'
OUT=ROOT/'results'; REPORT=ROOT/'reports'
OUT.mkdir(exist_ok=True); REPORT.mkdir(exist_ok=True)

def evaluate(df, methods):
    rows=[]
    for name,pred in methods.items():
        m=metric_bundle(df,pred); m.update(method=name,n=len(df)); rows.append(m)
    return rows

def conflict_accuracy(df):
    rank={'external_verified':5,'tool_verified':4,'explicit_user':3,'third_party':2,'inferred':1}
    good=total=0
    for _,g in df.groupby('conflict_group',dropna=True):
        if len(g)<2: continue
        score=g['provenance'].map(rank).fillna(0)+0.1*g['confidence'].astype(float)-10.0*(1-g['current'].astype(float))
        idx=score.idxmax(); gold=g['selected'].fillna(0).astype(int)
        if gold.sum()!=1: continue
        total+=1; good+=int(gold.loc[idx]==1)
    return good/total if total else float('nan')

def redact_provenance_cues(df):
    d=df.copy(); d['signal_content']='context signal'; return d

def main():
    df=pd.read_csv(DATA)
    train=df[df.split=='train'].copy(); val=df[df.split=='val'].copy()
    router=PLPRouter(include_provenance=True,random_state=7).fit(train,val)
    no_prov=PLPRouter(include_provenance=False,random_state=7).fit(redact_provenance_cues(train),redact_provenance_cues(val))
    eval_sets={
        'test':df[df.split=='test'].copy(),
        'ood_test':df[df.split=='ood_test'].copy(),
        'compositional_test':df[df.split=='compositional_test'].copy(),
    }
    pi=ROOT/'datasets/provenance/provenance_intervention_test.csv'
    if pi.exists(): eval_sets['provenance_intervention']=pd.read_csv(pi)

    summaries=[]; all_rows=[]; cal_rows=[]; errs=[]
    for split,d in eval_sets.items():
        learned=router.predict(d,hybrid=False); hybrid=router.predict(d,hybrid=True)
        methods={k:baseline_predictions(d,k) for k in ['naive','firewall','provenance_only','oracle']}
        methods['learned_plp']=learned; methods['hybrid_plp']=hybrid
        methods['learned_no_provenance']=no_prov.predict(redact_provenance_cues(d),hybrid=True)
        for r in evaluate(d,methods): r['split']=split; summaries.append(r)
        probs=router.predict_proba(d)
        joined=pd.concat([d.reset_index(drop=True),probs.reset_index(drop=True),learned.add_prefix('learned_').reset_index(drop=True),hybrid.add_prefix('hybrid_').reset_index(drop=True)],axis=1)
        joined['split_eval']=split; all_rows.append(joined)
        for target in LICENSE_COLS:
            tab=calibration_table(d[target].astype(int).to_numpy(),probs[target+'_prob'].to_numpy(),bins=10)
            tab.insert(0,'target',target); tab.insert(0,'split',split); cal_rows.append(tab)
        mismatch=(hybrid[LICENSE_COLS].to_numpy()!=d[LICENSE_COLS].astype(int).to_numpy()).any(axis=1)
        bad_positions=[i for i,b in enumerate(mismatch) if b]
        for pos in bad_positions:
            row=d.iloc[pos]; p=hybrid.iloc[pos]
            errs.append({'split':split,'case_id':row.case_id,'domain':row.domain,'task_kind':row.task_kind,'scope':row.scope,'provenance':row.provenance,'confidence':row.confidence,'current':row.current,'relevant':row.relevant,'gold':''.join(str(int(row[c])) for c in LICENSE_COLS),'pred':''.join(str(int(p[c])) for c in LICENSE_COLS)})

    summary=pd.DataFrame(summaries); summary.to_csv(OUT/'provenancebench_method_summary.csv',index=False)
    pd.concat(all_rows,ignore_index=True).to_csv(OUT/'provenancebench_predictions.csv',index=False)
    pd.concat(cal_rows,ignore_index=True).to_csv(OUT/'provenancebench_calibration.csv',index=False)
    pd.DataFrame(errs).to_csv(OUT/'provenancebench_errors.csv',index=False)
    head={k:{'threshold':v.threshold,'val_accuracy':v.val_accuracy,'val_brier':v.val_brier,'val_auc':v.val_auc} for k,v in router.head_results.items()}
    (OUT/'provenancebench_head_diagnostics.json').write_text(json.dumps(head,indent=2))
    conflicts={s:conflict_accuracy(df[df.split==s].copy()) for s in ['conflict_test','conflict_ood_test']}
    (OUT/'provenancebench_conflict_metrics.json').write_text(json.dumps(conflicts,indent=2))

    lines=['# ProvenanceBench — executable learned PLP evaluation','', 'Regenerated by `python scripts/run_provenancebench_learned.py`. Thresholds are selected only on `val`; all reported evaluation splits are untouched.','']
    for split in eval_sets:
        lines += [f'## {split}','', '| Method | Exact match ↑ | Evidence uptake ↑ | Unsupported leakage ↓ | Starvation ↓ |','|---|---:|---:|---:|---:|']
        for _,r in summary[summary.split==split].iterrows():
            lines.append(f"| {r.method} | {r.exact_license_match:.3f} | {r.evidence_uptake:.3f} | {r.unsupported_leakage:.3f} | {r.evidence_starvation:.3f} |")
        lines.append('')
    lines += ['## Conflict authority selection','',f"- ID conflict accuracy: {conflicts['conflict_test']:.3f}",f"- OOD conflict accuracy: {conflicts['conflict_ood_test']:.3f}",'','## Interpretation boundary','','These are controlled licensing results. They test whether routing separates personalization relevance from evidentiary permission; they do not establish full language-model generation quality or frontier-model SOTA.']
    (REPORT/'PROVENANCEBENCH_EXECUTABLE.md').write_text('\n'.join(lines))
    print(summary.to_string(index=False)); print('conflicts',conflicts)

if __name__=='__main__': main()
